// ============================================================
// DUMMY DATA - Modern Matrix AI Interview Monitoring System
// Matches the SDS GUI mockups exactly
// ============================================================

export const dummyUser = {
  id: 'usr-001',
  email: 'admin@modernmatrix.com',
  first_name: 'Kasun',
  last_name: 'Perera',
  role: 'Admin',
  avatar_url: null,
  created_at: '2026-01-10T08:00:00Z',
};

export const dummyUsers = [
  {
    id: 'usr-001',
    user_id_field: 'EMP-001',
    email: 'admin@modernmatrix.com',
    first_name: 'Kasun',
    last_name: 'Perera',
    role: 'Admin',
    is_locked: false,
    is_verified: true,
    created_at: '2026-01-10T08:00:00Z',
    sessions_count: 5,
  },
  {
    id: 'usr-002',
    user_id_field: 'EMP-002',
    email: 'hr.kavindi@modernmatrix.com',
    first_name: 'Kavindi',
    last_name: 'Senaratne',
    role: 'HR_Manager',
    is_locked: false,
    is_verified: true,
    created_at: '2026-02-01T09:30:00Z',
    sessions_count: 8,
  },
  {
    id: 'usr-003',
    user_id_field: 'EMP-003',
    email: 'hr.dinesh@modernmatrix.com',
    first_name: 'Dinesh',
    last_name: 'Bandara',
    role: 'HR_Manager',
    is_locked: false,
    is_verified: true,
    created_at: '2026-03-15T11:00:00Z',
    sessions_count: 4,
  },
  {
    id: 'usr-004',
    user_id_field: 'EMP-004',
    email: 'hr.amila@modernmatrix.com',
    first_name: 'Amila',
    last_name: 'Jayawardena',
    role: 'HR_Manager',
    is_locked: true,
    is_verified: true,
    created_at: '2026-04-01T14:20:00Z',
    sessions_count: 2,
  },
];

export const dummyCandidates = [
  {
    id: 'cand-001',
    full_name: 'Janith Perera',
    email: 'janith.perera@email.com',
    position: 'Software Engineer',
    status: 'Evaluated',
    date_registered: '2026-01-23',
    score: 90,
    notes: 'Strong technical background with 5 years of experience.',
    keywords: ['JavaScript', 'React', 'Node.js'],
    avatar_url: null,
  },
  {
    id: 'cand-002',
    full_name: 'Malith Fernando',
    email: 'malith.fernando@email.com',
    position: 'Marketing Manager',
    status: 'In Progress',
    date_registered: '2026-02-14',
    score: 89,
    notes: 'Excellent communication skills, leadership potential.',
    keywords: ['SEO', 'Content Strategy', 'Analytics'],
    avatar_url: null,
  },
  {
    id: 'cand-003',
    full_name: 'Ruwan Jayasinghe',
    email: 'ruwan.jayasinghe@email.com',
    position: 'HR Coordinator',
    status: 'Pending Review',
    date_registered: '2026-04-02',
    score: 77,
    notes: 'Good organizational skills, needs more experience.',
    keywords: ['Recruitment', 'Onboarding', 'HRIS'],
    avatar_url: null,
  },
  {
    id: 'cand-004',
    full_name: 'Nuwan Gunawardena',
    email: 'nuwan.gunawardena@email.com',
    position: 'Data Analyst',
    status: 'Rejected',
    date_registered: '2026-03-03',
    score: 68,
    notes: 'Technical skills need improvement.',
    keywords: ['SQL', 'Python', 'Tableau'],
    avatar_url: null,
  },
  {
    id: 'cand-005',
    full_name: 'Sachini Wickramasinghe',
    email: 'sachini.w@email.com',
    position: 'Product Manager',
    status: 'Evaluated',
    date_registered: '2026-01-11',
    score: 85,
    notes: 'Great product sense and stakeholder management.',
    keywords: ['Agile', 'Roadmap', 'User Research'],
    avatar_url: null,
  },
  {
    id: 'cand-006',
    full_name: 'Anuki Bandara',
    email: 'anuki.bandara@email.com',
    position: 'AI Specialist',
    status: 'Evaluated',
    date_registered: '2026-02-06',
    score: 80,
    notes: 'Strong ML background, good at explaining complex topics.',
    keywords: ['Machine Learning', 'NLP', 'TensorFlow'],
    avatar_url: null,
  },
];

export const dummyQuestions = [
  {
    id: 'q-001',
    question_text: 'Can you describe your experience with coding in Python?',
    category: 'Technical',
    difficulty: 'Medium',
    keywords: ['Python', 'Programming', 'Experience'],
    ai_scoring_enabled: true,
    weights: { honesty: 50, confidence: 50, attitude: 50, relevance: 50 },
  },
  {
    id: 'q-002',
    question_text: 'How do you debug a piece of code you didn\'t write?',
    category: 'Technical',
    difficulty: 'Hard',
    keywords: ['Debugging', 'Problem Solving', 'Code Review'],
    ai_scoring_enabled: true,
    weights: { honesty: 40, confidence: 60, attitude: 50, relevance: 50 },
  },
  {
    id: 'q-003',
    question_text: 'Discuss a challenging project you worked on recently.',
    category: 'Behavioral',
    difficulty: 'Medium',
    keywords: ['Challenge', 'Project Management', 'Problem Solving'],
    ai_scoring_enabled: true,
    weights: { honesty: 60, confidence: 50, attitude: 50, relevance: 40 },
  },
  {
    id: 'q-004',
    question_text: 'Explain a time when you used algorithms to solve a problem.',
    category: 'Technical',
    difficulty: 'Hard',
    keywords: ['Algorithms', 'Data Structures', 'Optimization'],
    ai_scoring_enabled: true,
    weights: { honesty: 50, confidence: 50, attitude: 40, relevance: 60 },
  },
  {
    id: 'q-005',
    question_text: 'What are your strengths as a software engineer?',
    category: 'Behavioral',
    difficulty: 'Easy',
    keywords: ['Strengths', 'Self Assessment', 'Skills'],
    ai_scoring_enabled: true,
    weights: { honesty: 60, confidence: 50, attitude: 50, relevance: 40 },
  },
  {
    id: 'q-006',
    question_text: 'How do you handle disagreements with team members?',
    category: 'Behavioral',
    difficulty: 'Medium',
    keywords: ['Teamwork', 'Conflict Resolution', 'Communication'],
    ai_scoring_enabled: true,
    weights: { honesty: 50, confidence: 40, attitude: 60, relevance: 50 },
  },
  {
    id: 'q-007',
    question_text: 'Describe your approach to learning new technologies.',
    category: 'Behavioral',
    difficulty: 'Easy',
    keywords: ['Learning', 'Adaptability', 'Growth'],
    ai_scoring_enabled: true,
    weights: { honesty: 50, confidence: 50, attitude: 50, relevance: 50 },
  },
  {
    id: 'q-008',
    question_text: 'How do you prioritize tasks when working on multiple projects?',
    category: 'Situational',
    difficulty: 'Medium',
    keywords: ['Time Management', 'Priority', 'Organization'],
    ai_scoring_enabled: true,
    weights: { honesty: 50, confidence: 50, attitude: 50, relevance: 50 },
  },
  {
    id: 'q-009',
    question_text: 'What is your experience with database optimization?',
    category: 'Technical',
    difficulty: 'Hard',
    keywords: ['SQL', 'Indexing', 'Optimization', 'Logs'],
    ai_scoring_enabled: true,
    weights: { honesty: 40, confidence: 50, attitude: 40, relevance: 70 },
  },
  {
    id: 'q-010',
    question_text: 'Explain the concept of RESTful API design.',
    category: 'Technical',
    difficulty: 'Medium',
    keywords: ['REST', 'API', 'HTTP', 'Design'],
    ai_scoring_enabled: true,
    weights: { honesty: 40, confidence: 50, attitude: 40, relevance: 70 },
  },
  {
    id: 'q-011',
    question_text: 'Tell me about a time you failed and what you learned.',
    category: 'Behavioral',
    difficulty: 'Medium',
    keywords: ['Failure', 'Learning', 'Resilience'],
    ai_scoring_enabled: true,
    weights: { honesty: 70, confidence: 40, attitude: 50, relevance: 40 },
  },
  {
    id: 'q-012',
    question_text: 'How would you explain a complex technical concept to a non-technical stakeholder?',
    category: 'Situational',
    difficulty: 'Medium',
    keywords: ['Communication', 'Simplification', 'Stakeholder'],
    ai_scoring_enabled: true,
    weights: { honesty: 40, confidence: 50, attitude: 60, relevance: 50 },
  },
  {
    id: 'q-013',
    question_text: 'What motivates you in your professional career?',
    category: 'Behavioral',
    difficulty: 'Easy',
    keywords: ['Motivation', 'Career Goals', 'Passion'],
    ai_scoring_enabled: true,
    weights: { honesty: 60, confidence: 50, attitude: 50, relevance: 40 },
  },
  {
    id: 'q-014',
    question_text: 'Describe your experience with CI/CD pipelines.',
    category: 'Technical',
    difficulty: 'Hard',
    keywords: ['CI/CD', 'DevOps', 'Automation', 'Jenkins'],
    ai_scoring_enabled: true,
    weights: { honesty: 40, confidence: 50, attitude: 40, relevance: 70 },
  },
  {
    id: 'q-015',
    question_text: 'How do you ensure code quality in your projects?',
    category: 'Technical',
    difficulty: 'Medium',
    keywords: ['Code Review', 'Testing', 'Quality Assurance'],
    ai_scoring_enabled: true,
    weights: { honesty: 50, confidence: 50, attitude: 50, relevance: 50 },
  },
];

export const dummyInterviewSessions = [
  {
    id: 'ses-001',
    candidate_id: 'cand-001',
    candidate_name: 'Janith Perera',
    user_id: 'usr-001',
    evaluator_name: 'Kasun Perera',
    session_date: '2026-04-22T09:00:00Z',
    duration_seconds: 1185, // 19m 45s
    questions_answered: 5,
    questions_total: 5,
    noise_level_db: 42,
    validation_status: true,
    status: 'Completed',
    position: 'Software Engineer',
    round: 'Round 1',
    question_ids: ['q-001', 'q-002', 'q-003', 'q-004', 'q-005'],
  },
  {
    id: 'ses-002',
    candidate_id: 'cand-002',
    candidate_name: 'Malith Fernando',
    user_id: 'usr-001',
    evaluator_name: 'Kasun Perera',
    session_date: '2026-04-20T14:00:00Z',
    duration_seconds: 1320,
    questions_answered: 5,
    questions_total: 5,
    noise_level_db: 38,
    validation_status: true,
    status: 'Completed',
    position: 'Marketing Manager',
    round: 'Round 1',
    question_ids: ['q-003', 'q-006', 'q-007', 'q-008', 'q-013'],
  },
  {
    id: 'ses-003',
    candidate_id: 'cand-003',
    candidate_name: 'Ruwan Jayasinghe',
    user_id: 'usr-001',
    evaluator_name: 'Kasun Perera',
    session_date: '2026-04-18T10:30:00Z',
    duration_seconds: 980,
    questions_answered: 4,
    questions_total: 5,
    noise_level_db: 55,
    validation_status: true,
    status: 'Pending Review',
    position: 'HR Coordinator',
    round: 'Round 1',
    question_ids: ['q-005', 'q-006', 'q-008', 'q-011', 'q-013'],
  },
  {
    id: 'ses-004',
    candidate_id: 'cand-004',
    candidate_name: 'Nuwan Gunawardena',
    user_id: 'usr-001',
    evaluator_name: 'Kasun Perera',
    session_date: '2026-04-15T11:00:00Z',
    duration_seconds: 750,
    questions_answered: 3,
    questions_total: 5,
    noise_level_db: 62,
    validation_status: false,
    status: 'Completed',
    position: 'Data Analyst',
    round: 'Round 1',
    question_ids: ['q-001', 'q-004', 'q-009', 'q-010', 'q-015'],
  },
  {
    id: 'ses-005',
    candidate_id: 'cand-005',
    candidate_name: 'Sachini Wickramasinghe',
    user_id: 'usr-001',
    evaluator_name: 'Kasun Perera',
    session_date: '2026-04-12T13:00:00Z',
    duration_seconds: 1100,
    questions_answered: 5,
    questions_total: 5,
    noise_level_db: 35,
    validation_status: true,
    status: 'Completed',
    position: 'Product Manager',
    round: 'Round 1',
    question_ids: ['q-003', 'q-007', 'q-008', 'q-011', 'q-012'],
  },
  {
    id: 'ses-006',
    candidate_id: 'cand-006',
    candidate_name: 'Anuki Bandara',
    user_id: 'usr-001',
    evaluator_name: 'Kasun Perera',
    session_date: '2026-04-10T15:30:00Z',
    duration_seconds: 1050,
    questions_answered: 5,
    questions_total: 5,
    noise_level_db: 40,
    validation_status: true,
    status: 'Completed',
    position: 'AI Specialist',
    round: 'Round 1',
    question_ids: ['q-001', 'q-002', 'q-004', 'q-009', 'q-014'],
  },
];

export const dummyBehavioralScores = {
  'ses-001': { honesty: 94, attitude: 89, confidence: 88, relevance: 91, overall: 90 },
  'ses-002': { honesty: 91, attitude: 90, confidence: 87, relevance: 88, overall: 89 },
  'ses-003': { honesty: 78, attitude: 80, confidence: 72, relevance: 78, overall: 77 },
  'ses-004': { honesty: 65, attitude: 70, confidence: 68, relevance: 69, overall: 68 },
  'ses-005': { honesty: 86, attitude: 88, confidence: 82, relevance: 84, overall: 85 },
  'ses-006': { honesty: 82, attitude: 78, confidence: 80, relevance: 80, overall: 80 },
};

export const dummyTranscripts = {
  'ses-001': `Q1: Can you describe your experience with coding in Python?
A: I've been working with Python for about five years now. I started using it for data analysis scripts and gradually moved into web development with Django and FastAPI. I'm particularly experienced with libraries like NumPy, Pandas, and I've done some work with machine learning using scikit-learn.

Q2: How do you debug a piece of code you didn't write?
A: First, I try to understand the overall architecture by reading documentation and comments. Then I use logging and breakpoints to trace the execution flow. I also look at test cases if they exist, and I use tools like git blame to understand the history of changes.

Q3: Discuss a challenging project you worked on recently.
A: Recently, I worked on migrating a monolithic application to microservices. The challenge was maintaining data consistency across services while minimizing downtime. We used event-driven architecture and implemented saga patterns for distributed transactions.

Q4: Explain a time when you used algorithms to solve a problem.
A: I optimized a search feature that was taking 30 seconds to return results. I implemented a trie data structure for autocomplete and used binary search with caching, which reduced the response time to under 200 milliseconds.

Q5: What are your strengths as a software engineer?
A: I'd say my biggest strengths are problem-solving and attention to detail. I enjoy breaking down complex problems into manageable pieces. I'm also a strong communicator, which helps when collaborating with cross-functional teams.`,
};

// Dashboard statistics (matches the mockup exactly)
export const dummyDashboardStats = {
  registeredCandidates: 145,
  pendingEvaluations: 12,
  interviewsThisWeek: 20,
  averagePerformanceScore: 83,
  completedSessions: 86,
  upcomingInterviews: 5,
  recentSessions: 10,
};

// Weekly activity data for the bar chart
export const dummyWeeklyActivity = {
  labels: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun', 'Mon', 'Tue', 'Wed'],
  data: [8, 12, 6, 15, 10, 3, 2, 9, 14, 7],
};

// System maintenance data
export const dummySystemStats = {
  serverCpu: 32,
  memoryUsage: 64,
  activeUsers: 27,
  uptimeDays: 14,
  databaseStatus: 'Connected',
  lastBackup: '12 Mar 2026 - 02:00AM',
  databaseSize: '2.3 GB',
  totalAdmins: 3,
  totalRecruiters: 12,
  totalInterviews: 8,
  recentErrors: 2,
  warnings: 5,
  lastSystemUpdate: '10 Mar 2026',
  twoFactorEnabled: true,
  passwordPolicy: 'Strong',
  activeSessions: 14,
};
